remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

theme: jekyll-theme-hacker
title: "Kemal's Website"
description: "My Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.PNG'
include: ["_pages"]

collections:
  blogpages:
    output: true